source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

platform :ios, '8.0'
use_frameworks!

abstract_target 'RACBaseServiceDemoTargets' do
    
    pod 'RACBaseServices', :git => 'https://github.com/MarkeJave/RACBaseServices.git', :tag => '1.0.0'
    
    target 'RACBaseServiceDemo' do
    end
end